version: '3.8'

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=crudpg
    volumes:
      - crud_pg_data:/bitnami/postgresql

  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=docker@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=docker
    depends_on:
      - postgres

volumes:
  crud_pg_data:
